version: "3"

services:
    ubuntu:
        build:
            context: ubuntu
            args:
                - UBUNTU_VERSION=18.04
                - CURRENT_TZ=US/Eastern
        image: ubuntu/1804tz
        container_name: ubuntu-1804tz
        environment:
            - TZ_DATA=US/Eastern
